### ISSUE TITLE
Use AppImage update information format for ISO updates

### ISSUE THREAD

**Issue by probonopd** [Nitrux/nitrux-current-bug-tracker#10]
If Nitrux ISOs would use the AppImage update information format for ISO updates, then all tools capable of updating AppImages (such as [AppImageUpdate](https://github.com/AppImage/AppImageUpdate)) could update Nitrux ISOs as well.

I think it would be great to standardize on one format for the update information, to enable for a rich ecosystem of compatible updater and system management tools.

However, Nitrux ISOs do something similar to using AppImage update information, but not quite:

```
me@host:~$ strings nitrux_release_testing.iso | grep zsync
http://88.198.66.58:8000/nitrux_release_testing.iso.zsync
```

`http://88.198.66.58:8000/nitrux_release_testing.iso.zsync` is not a valid update information as per https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information. 

`zsync|http://88.198.66.58:8000/nitrux_release_testing.iso.zsync` woud be.

**Comment by probonopd** [comment]
cc @TheAssassin

**Comment by TheAssassin** [comment]
@probonopd you can simply use zsync to update this kind of stuff I guess. This is out of scope of AppImageUpdate.

**Comment by probonopd** [comment]
> This is out of scope of AppImageUpdate.

No, I want AppImageUpdate to update also ISOs.

**Comment by TheAssassin** [comment]
AppImageUpdate updates AppImages. It's the "AppImage update information". I don't see the point... you could make a "ISOupdate" using libzsync2 for this different workflow.

**Comment by probonopd** [comment]
Since a type-1 AppImage is an ISO file, we already have all that is needed. No need for a separate set of tools. The same tools can be used to update the OS and its apps.

**Comment by TheAssassin** [comment]
@probonopd you should set up a demo somewhere, I guess.

**Comment by luis-lavaire** [comment]
We are using [znx](https://github.com/nitrux/znx) to manage the updates of the ISO images. As @TheAssassin pointed-out, `zsync` is the only thing we need; and that's what we use in `znx` already.

**Comment by probonopd** [comment]
Sometimes I really ask myself why everyone reinvents everything in the open source world... this means I need to use a different tool to update my system vs. my apps. More complicated...

**Comment by star-buck** [comment]
Whats the difference then what znx adds than zsync or appimageupdate?

**Comment by probonopd** [comment]
Yes, simply adding `zsync|` would make it compatible with the updating scheme used by AppImageUpdate.

**Comment by luis-lavaire** [comment]
@probonopd, we are not trying to reinvent the wheel. We just took this path from the beginning. Things are not more complicated actually; they are just different when you use znx.

However, as you mentioned; prefixing `zsync|` won't harm anyone, so I'll add it to our ISO. :wink:

**Comment by luis-lavaire** [comment]
[Done](https://github.com/Nitrux/mkiso/commit/d8f6b911f3259c1e9d219a92c005ff388a6b5767).
